### PR TITLE
Enabling Tidy

### PR DESCRIPTION
**Pull request by martinthomson**

### CODE REVIEW

**Comment by martinthomson** [comment]
@dontcallmedom do you want to port these checks to travis, or do you want to enable circle?

**Comment by dontcallmedom** [comment]
My preference would be to go with travis to avoid having to maintain multiple CI systems; but I probably won't have the cycle to look into porting it to Travis in the short term, so maybe you could start with Circle here, and once I get to porting it, we can consolidate back.

**Comment by martinthomson** [comment]
This now works with travis.  It's a shame that the linkchecker is so flaky.

**Comment by dontcallmedom** [comment]
great, thanks! note that build failed here due to an HTML validity error, not due to the link checker

**Comment by martinthomson** [comment]
I managed to find the validation error, fix that, check that the tidy check on travis was being triggered, and now it should all run cleanly.

**Comment by alvestrand** [comment]
@dontcallmedom and @martinthomson - is this PR OBE or is it still worth doing (and thus rebasing)?

**Comment by dontcallmedom** [comment]
I think it's been OBE since a lot of it has moved upstream to https://github.com/w3c/webrtc-respec-ci

**Pull request closed without merging**
