### PR TITLE
Add note about Webgl using preserveDrawingBuffer.

### PR DESCRIPTION
**Pull request by uysalere**
@yellowdoge PTAL.

### CODE REVIEW

**Comment by Pehrsons** [comment]
@uysalere is there a discussion about this somewhere that I missed, or what's the reason this is in the spec? I.e., can't we capture frames from the drawing buffer before it'd normally be thrown away?

My immediate thought is that this seems like an implementation detail that could be avoided.

**Comment by uysalere** [comment]
It came up in a bug discussion here: https://bugs.chromium.org/p/chromium/issues/detail?id=889385. I am not sure if Firefox supports it. If that is the case, I can dig into where the implementation differs in WebGL code.

**Comment by Pehrsons** [comment]
Firefox supports it. We do the readback on vsync before swapping buffers IIRC.

**Comment by Pehrsons** [comment]
@uysalere, ping

**Pull request merged**
